version: '3'
services:

  db:
    # MySQL Root User -> "root"
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dmesh
      MYSQL_USER: dmesh-api
      MYSQL_PASSWORD: nth1997
    ports:
      - 3306:3306
    volumes:
      - ./mock/dmesh-init.sql:/docker-entrypoint-initdb.d/dmesh-init.sql

  db-adminer:
    image: adminer:4
    restart: always
    ports:
      - 9000:8080
