version: '3'
services:

  db:
    # MySQL Root User -> "root"
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dmesh
      MYSQL_USER: dmesh-api
      MYSQL_PASSWORD: nth1997
    ports:
      - 3306:3306
    volumes:
      - ./mock/dmesh-init.sql:/docker-entrypoint-initdb.d/dmesh-init.sql

  db-adminer:
    image: adminer:4
    restart: always
    ports:
      - 9000:8080

  rabbitmq:
    # User: guest
    # Password: guest
    image: rabbitmq:3.8-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  dmesh-api:
    build:
      context: ./dmesh-api/
    image: dmesh-api
    restart: always
    ports:
      - 8081:8081
    environment:
      API_PORT: 8081
      MY_SQL_IP: db
      RABBIT_MQ_IP: rabbitmq
      DATALAKE_PATH: /DATALAKE
    volumes:
      - ./DATALAKE:/DATALAKE

  dmesh-jobs:
    build:
      context: ./dmesh-jobs/
    image: dmesh-jobs
    restart: always
    environment:
      MY_SQL_IP: db
      RABBIT_MQ_IP: rabbitmq
      DATALAKE_PATH: /DATALAKE
    volumes:
      - ./dmesh-jobs:/jobs
      - ./DATALAKE:/DATALAKE
